### testing API

### user

### post new user

post http://localhost:8000/api/v1/coordinator
Content-Type: application/json

{
"name" : "Brazzy",
"email": "b@b",
"password": "aaasss",
"role" : "coordinator",
"phone":"0422429599"
}


### login
post http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
"email": "a@a",
"password": "aaasss"
}