### testing API


### Login as admin
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "Admin123!"
}

### Login as worker
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
  "email": "worker3@com",
  "password": "UudGm#7NEc7"
}


###  create user endpoint test

POST http://localhost:8000/api/v1/users/createuser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2YThkN2NiYWRlNzY0Zjc0ZDBkM2FiYzMiLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2YzUiLCJpYXQiOjE3ODg0MTU4NDksImV4cCI6MTc4ODUwMjI0OX0.zHI9osICiY-5M6fVnkogLNN8w-au5mhNyH61AfkrVtU

{
   "name": "Test3 worker",
  "email": "worker3@com",
  "phone": "0422429549",
  "role": "worker"
}

###get all the users

GET http://localhost:8000/api/v1/users/readuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2YThkN2NiYWRlNzY0Zjc0ZDBkM2FiYzMiLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2YzUiLCJpYXQiOjE3ODg0MTU4NDksImV4cCI6MTc4ODUwMjI0OX0.zHI9osICiY-5M6fVnkogLNN8w-au5mhNyH61AfkrVtU
### patch request

Patch http://localhost:8000/api/v1/users/updateuser/6a8f69e8243d8766e6b2b9a3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2YThkN2NiYWRlNzY0Zjc0ZDBkM2FiYzMiLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2YzUiLCJpYXQiOjE3ODg0MTU4NDksImV4cCI6MTc4ODUwMjI0OX0.zHI9osICiY-5M6fVnkogLNN8w-au5mhNyH61AfkrVtU

{
   "name": "Jogn Cena",
  "email": "johntest@2com",
  "phone": "0420000014",
  "role": "teamLeader",
  "status": "inactive"
  
}


### update permission
PATCH http://localhost:8000/api/v1/users/updateuser/6a8f69e8243d8766e6b2b9a3/permissions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2YThkN2NiYWRlNzY0Zjc0ZDBkM2FiYzMiLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2YzUiLCJpYXQiOjE3ODg0MTU4NDksImV4cCI6MTc4ODUwMjI0OX0.zHI9osICiY-5M6fVnkogLNN8w-au5mhNyH61AfkrVtU


{
  "permissionNames": [ "user:update"
   
  ]
}


###  create Clients endpoint test

POST http://localhost:8000/api/v1/clients/createclient
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2YThkN2NiYWRlNzY0Zjc0ZDBkM2FiYzMiLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2YzUiLCJpYXQiOjE3ODg0MTU4NDksImV4cCI6MTc4ODUwMjI0OX0.zHI9osICiY-5M6fVnkogLNN8w-au5mhNyH61AfkrVtU


{
   "name": "test1 client",
  "phone": "0433298722",
  "address": "fsdfsdfsd",
  "createdBy": "6a8d7cbade764f74d0d3abc3",
  "notes":"Dementia",
  "email":"client@s"


}


###  Get Clients endpoint test

GET http://localhost:8000/api/v1/clients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2YThkN2NiYWRlNzY0Zjc0ZDBkM2FiYzMiLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2YzUiLCJpYXQiOjE3ODgzMDQ1NzYsImV4cCI6MTc4ODM5MDk3Nn0.KTzQ2DNMC6Ti0-NkxfgSxTdvoL8tGgmfsMNzZEh_mek


### get single client
GET http://localhost:8000/api/v1/clients/6a94186d43fd0d7581573e74
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2YThkN2NiYWRlNzY0Zjc0ZDBkM2FiYzMiLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2YzUiLCJpYXQiOjE3ODgzMDQ1NzYsImV4cCI6MTc4ODM5MDk3Nn0.KTzQ2DNMC6Ti0-NkxfgSxTdvoL8tGgmfsMNzZEh_mek

####update client

patch http://localhost:8000/api/v1/clients/updateclient/6a94186d43fd0d7581573e74
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2YThkN2NiYWRlNzY0Zjc0ZDBkM2FiYzMiLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2YzUiLCJpYXQiOjE3ODgzMDQ1NzYsImV4cCI6MTc4ODM5MDk3Nn0.KTzQ2DNMC6Ti0-NkxfgSxTdvoL8tGgmfsMNzZEh_mek


  {
   "name": "sundari ",
  "phone": "0422429500",
  "address": " 7 sdfsdfsd ",
  "notes":"Depression",
  "email":"client@ssa",
  "isActive": false


}


### create shift

post http://localhost:8000/api/v1/shifts/createshift
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2YThkN2NiYWRlNzY0Zjc0ZDBkM2FiYzMiLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2YzUiLCJpYXQiOjE3ODg0MTU4NDksImV4cCI6MTc4ODUwMjI0OX0.zHI9osICiY-5M6fVnkogLNN8w-au5mhNyH61AfkrVtU

{
  "workerId": "6a9a0d2dfdafb723f4e73de7",
    "clientId": "6a991090feece244b35fcc62" ,
    "location": "9 derwent park",
    "date": "2026-09-11",
    "startTime": "07:00",
   "endTime":"17:00",
    "breakMinutes": 30,
    "notes":" taking for shopping"
    }

  
### get all shifts
GET http://localhost:8000/api/v1/shifts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2YThkN2NiYWRlNzY0Zjc0ZDBkM2FiYzMiLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2YzUiLCJpYXQiOjE3ODg0ODc3NjgsImV4cCI6MTc4ODU3NDE2OH0.tSohFv1I4HnvOG9juaDsmA2kZMJn-Enr-fkIBER6yHs

### get single shift
GET  http://localhost:8000/api/v1/shifts/6a9522122b8ab61de518a538
Authorization: Bearer 
### patch shift

Patch http://localhost:8000/api/v1/shifts/6a9522122b8ab61de518a538
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2YThkN2NiYWRlNzY0Zjc0ZDBkM2FiYzMiLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2YzUiLCJpYXQiOjE3ODgzMDQ1NzYsImV4cCI6MTc4ODM5MDk3Nn0.KTzQ2DNMC6Ti0-NkxfgSxTdvoL8tGgmfsMNzZEh_mek

{
  "workerId": "6a8f69e8243d8766e6b2b9a3",
    "clientId": "6a9418ea7482e4d3c8c49ec4" ,
    "location": "8 behhhdy road",
    "date": "2026-09-10",
    "startTime": "07:00",
   "endTime":"17:00",
    "breakMinutes": 30,
    "notes":" taking for shopping"
    }


### Delete shift

Delete http://localhost:8000/api/v1/shifts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiaWQiOiI2YThkN2NiYWRlNzY0Zjc0ZDBkM2FiYzMiLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2YzUiLCJpYXQiOjE3ODgzMDQ1NzYsImV4cCI6MTc4ODM5MDk3Nn0.KTzQ2DNMC6Ti0-NkxfgSxTdvoL8tGgmfsMNzZEh_mek

{
  "shiftIds":
  ["6a952d9109ad74f304e04e17"]
}


### Eligible check for swapShift

post http://localhost:8000/api/v1/swapShift/eligibileshift
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndvcmtlcjNAY29tIiwiaWQiOiI2YTlhMGQyZGZkYWZiNzIzZjRlNzNkZTciLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2Y2UiLCJpYXQiOjE3ODg0ODEwODcsImV4cCI6MTc4ODU2NzQ4N30.mYwoGhbfRCPYxF3neMLpfkzbdZNCIW3z2fEmIGYH_RU

{
  "targetedDate": "2026-09-16",
  "requestedShiftId": "6a9a0dd5fdafb723f4e73de8"
  
    }


###create swap request

post http://localhost:8000/api/v1/swapShift/createSwapShift
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndvcmtlcjNAY29tIiwiaWQiOiI2YTlhMGQyZGZkYWZiNzIzZjRlNzNkZTciLCJyb2xlSWQiOiI2YTg5ODUyZDg2ZThiYTRhZTczZmU2Y2UiLCJpYXQiOjE3ODg0ODEwODcsImV4cCI6MTc4ODU2NzQ4N30.mYwoGhbfRCPYxF3neMLpfkzbdZNCIW3z2fEmIGYH_RU

{
 "requestedShiftId" : "6a9a0dd5fdafb723f4e73de8",
 "targetedShiftId" : "6a9a0c8ffdafb723f4e73de5"
  
    }